name: Go Test and Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install dependencies
      run: |
         go mod download
         go mod verify
    - name: Check formatting (go fmt)
      run: |
        if [ -n "$(gofmt -l .)"]; then
          echo "Styleguide Go Error"
          gofmt -l .
          exit 1
        fi

    - name: Run tests
      run: go test -v ./...

    - name: Build main package
      run: go build -v -o /dev/null .

